// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASiRJqdrhKbUa-rUbur07zbpFfdb_41og',
    appId: '1:198028372788:web:114025bec1ab9d6999d361',
    messagingSenderId: '198028372788',
    projectId: 'educare4-eb83e',
    authDomain: 'educare4-eb83e.firebaseapp.com',
    databaseURL: 'https://educare4-eb83e-default-rtdb.firebaseio.com',
    storageBucket: 'educare4-eb83e.firebasestorage.app',
    measurementId: 'G-6S8S49JPN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANFq3wJBHC16FVzuV-_RMRCsf4EjkoTRo',
    appId: '1:198028372788:android:8806c139c8f6143899d361',
    messagingSenderId: '198028372788',
    projectId: 'educare4-eb83e',
    databaseURL: 'https://educare4-eb83e-default-rtdb.firebaseio.com',
    storageBucket: 'educare4-eb83e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrZTr2Eo-_w3QV8CmclhyaMrEsqupiVbA',
    appId: '1:198028372788:ios:9b65461930ec5b8a99d361',
    messagingSenderId: '198028372788',
    projectId: 'educare4-eb83e',
    databaseURL: 'https://educare4-eb83e-default-rtdb.firebaseio.com',
    storageBucket: 'educare4-eb83e.firebasestorage.app',
    iosBundleId: 'com.example.educare4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrZTr2Eo-_w3QV8CmclhyaMrEsqupiVbA',
    appId: '1:198028372788:ios:9b65461930ec5b8a99d361',
    messagingSenderId: '198028372788',
    projectId: 'educare4-eb83e',
    databaseURL: 'https://educare4-eb83e-default-rtdb.firebaseio.com',
    storageBucket: 'educare4-eb83e.firebasestorage.app',
    iosBundleId: 'com.example.educare4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASiRJqdrhKbUa-rUbur07zbpFfdb_41og',
    appId: '1:198028372788:web:d0da94bf9294cfb499d361',
    messagingSenderId: '198028372788',
    projectId: 'educare4-eb83e',
    authDomain: 'educare4-eb83e.firebaseapp.com',
    databaseURL: 'https://educare4-eb83e-default-rtdb.firebaseio.com',
    storageBucket: 'educare4-eb83e.firebasestorage.app',
    measurementId: 'G-Y487CHFH9C',
  );

}